import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'data/datasources/task_local_data_source.dart';
import 'data/models/task_model.dart';
import 'data/repositories/task_repository_impl.dart';
import 'domain/usecases/task_usecases.dart';
import 'presentation/bloc/task_cubit.dart';
import 'presentation/pages/task_list_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Hive
  await Hive.initFlutter();
  
  // Register Adapter (generated by build_runner)
  Hive.registerAdapter(TaskModelAdapter());
  
  // Setup Data layer
  final localDataSource = TaskLocalDataSourceImpl();
  final repository = TaskRepositoryImpl(localDataSource: localDataSource);
  
  // Setup Domain layer
  final getTasksUseCase = GetTasksUseCase(repository);
  final addTaskUseCase = AddTaskUseCase(repository);
  final updateTaskUseCase = UpdateTaskUseCase(repository);
  final deleteTaskUseCase = DeleteTaskUseCase(repository);

  runApp(
    MyApp(
      getTasksUseCase: getTasksUseCase,
      addTaskUseCase: addTaskUseCase,
      updateTaskUseCase: updateTaskUseCase,
      deleteTaskUseCase: deleteTaskUseCase,
    ),
  );
}

class MyApp extends StatelessWidget {
  final GetTasksUseCase getTasksUseCase;
  final AddTaskUseCase addTaskUseCase;
  final UpdateTaskUseCase updateTaskUseCase;
  final DeleteTaskUseCase deleteTaskUseCase;

  const MyApp({
    super.key,
    required this.getTasksUseCase,
    required this.addTaskUseCase,
    required this.updateTaskUseCase,
    required this.deleteTaskUseCase,
  });

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => TaskCubit(
        getTasksUseCase: getTasksUseCase,
        addTaskUseCase: addTaskUseCase,
        updateTaskUseCase: updateTaskUseCase,
        deleteTaskUseCase: deleteTaskUseCase,
      ),
      child: MaterialApp(
        title: 'Task Space',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(
            seedColor: const Color(0xFF2575FC),
            primary: const Color(0xFF2575FC),
            secondary: const Color(0xFF6A11CB),
          ),
          useMaterial3: true,
        ),
        home: const TaskListPage(),
      ),
    );
  }
}
